/**
 * AIM Instagram Suite — Tool: aim_create_style
 * Интерактивный мастер создания кастомного стиля карусели.
 * Работает как многошаговый опрос через Claude с выбором вариантов.
 *
 * ШАГ 1 → Настроение / Вайб
 * ШАГ 2 → Цветовая схема
 * ШАГ 3 → Типографика
 * ШАГ 4 → Контентный стиль
 * ФИНАЛ → Генерация CSS + конфига стиля
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export interface CreateStyleInput {
  step?: 1 | 2 | 3 | 4 | 5;
  /** Шаг 1: настроение */
  mood?: 'luxury' | 'energetic' | 'minimal' | 'warm' | 'dark' | 'playful';
  /** Шаг 2: цветовая схема */
  colorBase?: 'dark' | 'light' | 'contrast';
  primaryHex?: string;
  secondaryHex?: string;
  /** Шаг 3: типографика */
  fontStyle?: 'serif' | 'modern' | 'bold' | 'handwritten' | 'mono';
  /** Шаг 4: подача контента */
  contentDensity?: 'minimal' | 'balanced' | 'rich';
  emojiUsage?: 'none' | 'subtle' | 'expressive';
  /** Финал */
  customWishes?: string;
  styleName?: string;
  /** Путь для сохранения стиля */
  saveToPath?: string;
}

// ── Опции для каждого шага ───────────────────────────────────────────────────

const MOODS = {
  luxury:    { label: '✨ Luxury / Premium',    baseTheme: 5, desc: 'Чёрный, золото, минимализм. Дорого и сдержанно.' },
  energetic: { label: '💥 Energetic / Bold',   baseTheme: 2, desc: 'Яркие цвета, мощные шрифты. Энергия и действие.' },
  minimal:   { label: '🤍 Clean / Minimal',     baseTheme: 3, desc: 'Много воздуха, тонкие линии. Спокойно и элегантно.' },
  warm:      { label: '🌸 Warm / Friendly',     baseTheme: 7, desc: 'Тёплые тона, дружелюбный стиль. Близость к аудитории.' },
  dark:      { label: '🌙 Dark / Mysterious',   baseTheme: 4, desc: 'Тёмный фон, неоновые акценты. Загадочность и глубина.' },
  playful:   { label: '🎨 Playful / Creative',  baseTheme: 6, desc: 'Y2K эстетика, смелые комбинации. Творчество и игра.' },
};

const FONT_STYLES = {
  serif:       { label: '📖 Классика (Georgia/Playfair)', fonts: ['Playfair Display', 'Cormorant Garamond'], desc: 'Авторитет, традиции, глубина' },
  modern:      { label: '🔵 Современный (Inter/Manrope)', fonts: ['Inter', 'Manrope'],                       desc: 'Чистота, технологичность, доверие' },
  bold:        { label: '💪 Жирный (Montserrat/Oswald)',  fonts: ['Montserrat', 'Oswald'],                   desc: 'Уверенность, сила, влияние' },
  handwritten: { label: '✍️ Рукописный (Caveat/Satisfy)',  fonts: ['Caveat', 'Satisfy'],                      desc: 'Личность, искренность, творчество' },
  mono:        { label: '💻 Моно (Space Mono/Fira)',      fonts: ['Space Mono', 'Fira Code'],                desc: 'Технологии, точность, экспертность' },
};

// ── Генератор CSS стиля ──────────────────────────────────────────────────────

function buildCSS(input: CreateStyleInput): string {
  const mood = MOODS[input.mood ?? 'luxury'];
  const font = FONT_STYLES[input.fontStyle ?? 'modern'];

  // Цветовая схема
  const primary   = input.primaryHex   ?? getDefaultPrimary(input.mood ?? 'luxury');
  const secondary = input.secondaryHex ?? getDefaultSecondary(input.mood ?? 'luxury');
  const bg        = getBackground(input.colorBase ?? 'dark', input.mood ?? 'luxury');
  const textColor = getTextColor(input.colorBase ?? 'dark');

  const fontFamily = `'${font.fonts[0]}', '${font.fonts[1]}', sans-serif`;
  const googleFonts = font.fonts.map(f => f.replace(/ /g, '+')).join('&family=');

  return `/* AIM Custom Style: ${input.styleName ?? 'My Style'} */
/* Generated by aim_create_style | Mood: ${mood.label} | Font: ${font.label} */

@import url('https://fonts.googleapis.com/css2?family=${googleFonts}&display=swap');

:root {
  --color-bg:         ${bg.main};
  --color-bg-card:    ${bg.card};
  --color-primary:    ${primary};
  --color-secondary:  ${secondary};
  --color-text:       ${textColor.main};
  --color-text-muted: ${textColor.muted};
  --color-accent:     ${primary};
  --color-border:     ${primary}33;

  --font-family-heading: ${fontFamily};
  --font-family-body:    ${fontFamily};

  --font-size-hero:     ${input.contentDensity === 'minimal' ? '72px' : '64px'};
  --font-size-title:    ${input.contentDensity === 'minimal' ? '48px' : '40px'};
  --font-size-body:     ${input.contentDensity === 'rich' ? '20px' : '18px'};

  --border-radius:  ${input.mood === 'minimal' ? '4px' : input.mood === 'playful' ? '20px' : '12px'};
  --shadow:         ${getShadow(input.mood ?? 'luxury', primary)};
  --animation-in:   fadeSlideUp 0.4s ease;
}

body, .slide {
  background: var(--color-bg) !important;
  font-family: var(--font-family-body) !important;
  color: var(--color-text) !important;
}

.slide-title, h1, h2 {
  font-family: var(--font-family-heading) !important;
  color: var(--color-primary) !important;
  font-weight: ${input.fontStyle === 'bold' ? '900' : '700'};
  letter-spacing: ${input.fontStyle === 'mono' ? '0.05em' : '-0.02em'};
}

.slide-body, p {
  color: var(--color-text-muted) !important;
  line-height: ${input.contentDensity === 'rich' ? '1.8' : '1.6'};
}

.hero-number, .big-stat {
  color: var(--color-primary) !important;
  text-shadow: 0 0 40px ${primary}66;
}

.tag, .badge {
  background: ${primary}22 !important;
  color: var(--color-primary) !important;
  border: 1px solid ${primary}44 !important;
  border-radius: 999px;
}

.card, .block {
  background: var(--color-bg-card) !important;
  border: 1px solid var(--color-border) !important;
  border-radius: var(--border-radius) !important;
  box-shadow: var(--shadow) !important;
}

.block-good, .check-item {
  border-left: 3px solid var(--color-primary) !important;
}

.block-bad {
  border-left: 3px solid ${secondary} !important;
  opacity: 0.85;
}

.cta-banner {
  background: linear-gradient(90deg, ${primary}, ${secondary}) !important;
  color: #fff !important;
  font-weight: 700;
}

.slide-emoji {
  display: ${input.emojiUsage === 'none' ? 'none' : 'block'} !important;
  font-size: ${input.emojiUsage === 'expressive' ? '56px' : '40px'} !important;
}

@keyframes fadeSlideUp {
  from { opacity: 0; transform: translateY(16px); }
  to   { opacity: 1; transform: translateY(0); }
}`;
}

// ── Вспомогательные цветовые функции ────────────────────────────────────────

function getDefaultPrimary(mood: string): string {
  const map: Record<string, string> = {
    luxury: '#C9A84C', energetic: '#FF3D00', minimal: '#1A1A1A',
    warm: '#E07B54', dark: '#00FF9F', playful: '#FF6EC7',
  };
  return map[mood] ?? '#8B5CF6';
}

function getDefaultSecondary(mood: string): string {
  const map: Record<string, string> = {
    luxury: '#8B6914', energetic: '#FF8C00', minimal: '#888888',
    warm: '#F4A261', dark: '#00D4FF', playful: '#A78BFA',
  };
  return map[mood] ?? '#4F46E5';
}

function getBackground(base: string, mood: string) {
  if (base === 'light') return { main: '#FAFAF9', card: '#FFFFFF' };
  if (base === 'contrast') return { main: '#000000', card: '#111111' };
  // dark (default)
  const moodBg: Record<string, { main: string; card: string }> = {
    luxury:    { main: '#0A0A0A', card: '#141414' },
    energetic: { main: '#0D0D0D', card: '#1A0505' },
    minimal:   { main: '#F8F8F6', card: '#FFFFFF' },
    warm:      { main: '#1A0F0A', card: '#251510' },
    dark:      { main: '#050510', card: '#0A0A1E' },
    playful:   { main: '#0D0010', card: '#180020' },
  };
  return moodBg[mood] ?? { main: '#0A0A0A', card: '#141414' };
}

function getTextColor(base: string) {
  if (base === 'light') return { main: '#1A1A1A', muted: '#6B6B6B' };
  return { main: '#F0F0F0', muted: '#9CA3AF' };
}

function getShadow(mood: string, primary: string): string {
  if (mood === 'luxury') return `0 8px 32px rgba(0,0,0,0.6)`;
  if (mood === 'energetic') return `4px 4px 0px ${primary}`;
  if (mood === 'dark') return `0 0 20px ${primary}40`;
  if (mood === 'playful') return `6px 6px 0px ${primary}`;
  return `0 4px 16px rgba(0,0,0,0.2)`;
}

export async function createStyle(input: CreateStyleInput): Promise<string> {
  const step = input.step ?? 1;

  // ── ШАГ 1: Настроение ────────────────────────────────────────────────────
  if (step === 1) {
    return JSON.stringify({
      tool: 'aim_create_style',
      step: 1,
      wizard: '🎨 Мастер создания стиля AIM — Шаг 1 из 4',
      question: 'Какое ощущение должна создавать твоя карусель?',
      instruction: 'Покажи пользователю эти варианты в виде красивого нумерованного списка-меню, как "кнопки". Предложи выбрать одну цифру. ОБЯЗАТЕЛЬНО ЖДИ ОТВЕТА ПОЛЬЗОВАТЕЛЯ, не продолжай сам.',
      choices: Object.entries(MOODS).map(([id, m], i) => ({
        number: i + 1,
        id,
        label: m.label,
        description: m.desc,
      })),
      nextCall: 'После ответа вызови aim_create_style со { step: 2, mood: "<выбранный id>" }',
    }, null, 2);
  }

  // ── ШАГ 2: Цвета ─────────────────────────────────────────────────────────
  if (step === 2) {
    if (!input.mood) return JSON.stringify({ error: 'Укажи mood из шага 1' });

    const moodData = MOODS[input.mood];
    return JSON.stringify({
      tool: 'aim_create_style',
      step: 2,
      wizard: `🎨 Шаг 2 из 4 — Цвета (выбрано: ${moodData.label})`,
      question: 'Настрой цветовую схему:',
      instruction: 'Оформи этот шаг как интерактивные "кнопки" (номер списка с жирным текстом). Задай пользователю три уточняющих вопроса сразу:\n1. Фон (1, 2, 3)?\n2. Основной цвет HEX?\n3. Вторичный цвет HEX?',
      colorBaseOptions: [
        { number: 1, id: 'dark',     label: '🌙 Тёмный фон (рекомендуется)' },
        { number: 2, id: 'light',    label: '☀️ Светлый фон' },
        { number: 3, id: 'contrast', label: '⬛ Максимальный контраст (чёрный)' },
      ],
      moodDefaults: {
        primary:   getDefaultPrimary(input.mood),
        secondary: getDefaultSecondary(input.mood),
        note: 'Если цвета не указаны, я подберу их сам (оставь пустыми)',
      },
      nextCall: 'После ответов (когда юзер введет цифру фона и/или цвета), вызови aim_create_style со { step: 3, ... }',
    }, null, 2);
  }

  // ── ШАГ 3: Типографика ───────────────────────────────────────────────────
  if (step === 3) {
    return JSON.stringify({
      tool: 'aim_create_style',
      step: 3,
      wizard: '🎨 Шаг 3 из 4 — Шрифт и типографика',
      question: 'Какой стиль шрифта соответствует твоему блогу?',
      instruction: 'Покажи как нумерованное меню-"кнопки" для выбора.',
      choices: Object.entries(FONT_STYLES).map(([id, f], i) => ({
        number: i + 1,
        id,
        label: f.label,
        description: f.desc,
        fonts: f.fonts,
      })),
      nextCall: 'Вызови aim_create_style со { step: 4, ...предыдущие параметры..., fontStyle: "<выбранный id>" }',
    }, null, 2);
  }

  // ── ШАГ 4: Подача контента ───────────────────────────────────────────────
  if (step === 4) {
    return JSON.stringify({
      tool: 'aim_create_style',
      step: 4,
      wizard: '🎨 Шаг 4 из 4 — Подача и детали',
      questions: [
        {
          id: 'contentDensity',
          question: 'Сколько текста на слайде?',
          choices: [
            { id: 'minimal',   label: '✨ Минимум — только суть, крупно и чисто' },
            { id: 'balanced',  label: '⚖️ Баланс — заголовок + 2-3 строки'       },
            { id: 'rich',      label: '📝 Насыщенно — подробные объяснения'      },
          ],
        },
        {
          id: 'emojiUsage',
          question: 'Как использовать эмодзи?',
          choices: [
            { id: 'none',       label: '🚫 Без эмодзи — строго и профессионально' },
            { id: 'subtle',     label: '😊 Умеренно — только для акцентов'        },
            { id: 'expressive', label: '🎉 Активно — везде для вовлечения'        },
          ],
        },
        {
          id: 'customWishes',
          question: '💬 Есть дополнительные пожелания к стилю? (необязательно)',
          type: 'free_text',
          placeholder: 'Например: "Хочу чтобы была тонкая золотая линия под заголовком" или "Добавь паттерн сетки на фон"',
        },
        {
          id: 'styleName',
          question: '📛 Как назвать этот стиль?',
          type: 'free_text',
          placeholder: 'Например: "Мой Premium Black" или "Стиль для кафе Sofia"',
        },
      ],
      nextCall: 'Вызови aim_create_style со { step: 5, ...все предыдущие..., contentDensity, emojiUsage, customWishes, styleName }',
    }, null, 2);
  }

  // ── ШАГ 5: ФИНАЛ — генерация стиля ──────────────────────────────────────
  if (step === 5) {
    const css = buildCSS(input);
    const moodData = MOODS[input.mood ?? 'luxury'];
    const fontData = FONT_STYLES[input.fontStyle ?? 'modern'];

    const styleConfig = {
      name:          input.styleName ?? 'My AIM Style',
      version:       '1.0',
      createdAt:     new Date().toISOString(),
      settings: {
        mood:           input.mood,
        colorBase:      input.colorBase,
        primaryHex:     input.primaryHex ?? getDefaultPrimary(input.mood ?? 'luxury'),
        secondaryHex:   input.secondaryHex ?? getDefaultSecondary(input.mood ?? 'luxury'),
        fontStyle:      input.fontStyle,
        contentDensity: input.contentDensity,
        emojiUsage:     input.emojiUsage,
        customWishes:   input.customWishes ?? null,
      },
      render: {
        recommendedBaseTheme: moodData.baseTheme,
        brandColorOverlay:    css,
        recommendedLayout:    getRecommendedLayout(input),
        recommendedFormat:    input.mood === 'minimal' ? 'square' : 'portrait',
      },
    };

    // Сохраняем если указан путь
    let savedPath: string | null = null;
    if (input.saveToPath) {
      try {
        fs.writeFileSync(input.saveToPath, JSON.stringify(styleConfig, null, 2), 'utf-8');
        savedPath = input.saveToPath;
      } catch (e) {
        // ignore
      }
    } else {
      // Сохраняем в ~/.aim_styles/
      const stylesDir = path.join(os.homedir(), '.aim_styles');
      if (!fs.existsSync(stylesDir)) fs.mkdirSync(stylesDir, { recursive: true });
      const safeName = (input.styleName ?? 'my_style').replace(/[^a-zA-Z0-9а-яА-Я_\- ]/g, '').replace(/ /g, '_');
      savedPath = path.join(stylesDir, `${safeName}.json`);
      fs.writeFileSync(savedPath, JSON.stringify(styleConfig, null, 2), 'utf-8');
    }

    // ==== ГЕНЕРАЦИЯ PREVIEW ====
    // Создаем демо HTML с этим кастомным стилем
    const tmpDir = path.join(os.tmpdir(), `aim_preview_${Date.now()}`);
    fs.mkdirSync(tmpDir, { recursive: true });
    
    // Подготовим фейковый HTML для демо-слайда
    const demoHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          /* Base Renderer CSS (simplified version of htmlRenderer template) */
          * { box-sizing: border-box; }
          body { margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; background: #333; height: 100vh; font-family: sans-serif; }
          .carousel-container { display: flex; gap: 40px; }
          .slide { width: 1080px; height: 1350px; background: #000; position: relative; overflow: hidden; display: flex; flex-direction: column; padding: 80px; }
          .tag { display: inline-block; padding: 12px 24px; border-radius: 9999px; font-size: 24px; font-weight: 700; margin-bottom: 40px; }
          .slide-title { font-size: 80px; font-weight: 800; line-height: 1.1; margin: 0 0 40px 0; letter-spacing: -0.02em; }
          .slide-body { font-size: 32px; line-height: 1.5; opacity: 0.9; margin: 0 0 60px 0; }
          .card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; padding: 40px; margin-bottom: 40px; }
          .card-title { font-size: 36px; font-weight: 700; margin: 0 0 20px 0; }
          .card-text { font-size: 28px; opacity: 0.8; margin: 0; }
          .cta-banner { position: absolute; bottom: 80px; left: 80px; right: 80px; padding: 40px; text-align: center; border-radius: 20px; font-size: 36px; font-weight: bold; display: flex; justify-content: space-between; align-items: center; }
          .slide-number { position: absolute; top: 80px; right: 80px; font-size: 28px; opacity: 0.5; font-weight: bold; }
          .check-item { display: flex; align-items: flex-start; gap: 20px; font-size: 30px; margin-bottom: 20px; }
          
          /* Вставляем сгенерированный кастомный стиль! */
          ${css}
        </style>
      </head>
      <body>
        <div class="carousel-container">
          <div class="slide">
            <div class="slide-number">Style Preview</div>
            <div>
              <span class="tag"># ${styleConfig.name.toUpperCase()}</span>
            </div>
            <h1 class="slide-title">Визуальный<br>Style Guide<br>Для Карусели</h1>
            <p class="slide-body">
              Именно так будут выглядеть ваши будущие посты. Заголовок, 
              шрифты, теги и цвета уже настроены под выбранный vibe (${moodData.label}).
            </p>
            <div class="card">
              <h3 class="card-title">Демонстрация Инфоблока</h3>
              <div class="check-item">
                <span>Primary Color: <b>${styleConfig.settings.primaryHex}</b></span>
              </div>
              <div class="check-item" style="border-left-color: var(--color-secondary) !important">
                <span>Secondary Color: <b>${styleConfig.settings.secondaryHex}</b></span>
              </div>
            </div>
            <div class="cta-banner">
              <span>Сохраняйте в закладки 👇</span>
              <span style="font-size: 48px">↗️</span>
            </div>
          </div>
        </div>
      </body>
      </html>
    `;
    
    let previewBase64 = null;
    try {
      const htmlPath = path.join(tmpDir, 'preview.html');
      fs.writeFileSync(htmlPath, demoHtml, 'utf-8');
      
      console.error('[AIM] Рендерим демо-слайд для Style Creator...');
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const puppeteer = require('puppeteer');
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      });
      const page = await browser.newPage();
      await page.setViewport({ width: 1080, height: 1350, deviceScaleFactor: 1 });
      await page.goto(`file://${htmlPath}`, { waitUntil: 'networkidle0', timeout: 30000 });
      
      // Ждём шрифты
      await Promise.race([
        page.evaluateHandle('document.fonts.ready'),
        new Promise(r => setTimeout(r, 3000))
      ]);
      
      const imgPath = path.join(tmpDir, 'preview.jpeg');
      await page.screenshot({ path: imgPath, type: 'jpeg', quality: 90 });
      await browser.close();
      
      const imgBuffer = fs.readFileSync(imgPath);
      previewBase64 = imgBuffer.toString('base64');
    } catch (err) {
      console.error('[AIM] Ошибка рендера превью:', err);
    }

    return JSON.stringify({
      tool: 'aim_create_style',
      step: 'complete',
      success: true,
      styleName: styleConfig.name,

      summary: {
        mood:    moodData.label,
        font:    fontData.label,
        primary: styleConfig.settings.primaryHex,
        base:    input.colorBase ?? 'dark',
        density: input.contentDensity,
      },

      savedTo: savedPath,

      howToUse: {
        step1: `Создай структуру карусели: aim_draft_carousel_structure с topic="..."`,
        step2: `Передай в aim_render_premium_carousel:`,
        renderParams: {
          theme:             moodData.baseTheme,
          format:            styleConfig.render.recommendedFormat,
          brandColorOverlay: '← используй сгенерированный CSS',
        },
      },
      
      // Если отрендерилось превью - кидаем в вывод (index.ts подхватит его)
      ...(previewBase64 ? {
        stylePreview: {
          mimeType: 'image/jpeg',
          base64: previewBase64,
          description: `Визуальное превью для стиля: ${styleConfig.name}`,
        }
      } : {}),

      brandColorOverlay: css,

      // Инструкция для ИИ
      nextAction: 'Покажи параметры финального стиля. Картинка-превью уже приложена выше. Спроси пользователя, хочет ли он теперь создать черновик карусели в этом стиле (нажав/написав "Да").',
    }, null, 2);
  }

  return JSON.stringify({ error: `Неизвестный шаг: ${step}. Укажи step от 1 до 5.` });
}

function getRecommendedLayout(input: CreateStyleInput): string[] {
  const layouts: string[] = ['standard'];
  if (input.contentDensity === 'minimal') layouts.push('hero-number', 'quote');
  if (input.contentDensity === 'rich') layouts.push('checklist', 'comparison');
  if (input.mood === 'energetic' || input.mood === 'playful') layouts.push('good-bad', 'before-after');
  layouts.push('cta-final');
  return layouts;
}
